[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/ai"
  to = "/.netlify/functions/ai"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
